def complex(num1, num2, operand):
    if operand == 1:
        return num1 + num2
    elif operand == 2:
        return num1 - num2
    elif operand == 3:
        return num1 * num2
    elif operand == 4:
        return num1 / num2